name: deploy-docs

on:
  push:
    branches:
    - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install project and dependencies
      run: pip install -e .[docs]

    - name: Cache executed notebooks
      uses: actions/cache@v4
      with:
        path: docs/_build/.jupyter_cache
        key: jupyter-cache-${{ hashFiles('pyproject.toml') }}
        restore-keys: jupyter-cache-

    - name: Build the docs
      run: sphinx-build -b html docs docs/_build/html

    - name: Upload as a GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
